# Generated by Django 4.2.6 on 2023-10-09 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 11, 12, 28, 937223, tzinfo=datetime.timezone.utc)),
        ),
    ]
